# 50 curated seed prompts for GSM8K-style math reasoning
SEED_PROMPTS = [
    "Let's solve this step by step, writing each calculation clearly before the final answer.",
    "Think carefully: restate the problem, identify knowns and unknowns, and plan the steps.",
    "Break the problem into parts: what is asked, what is given, and which operations are needed.",
    "Use units consistently and show intermediate results with units.",
    "List relevant quantities, then compute them in order, verifying each intermediate value.",
    "Solve using a table of values for each step; summarize at the end.",
    "Start with definitions, then derive the result with simple arithmetic.",
    "Draw a mental picture: translate words into numbers, then compute.",
    "Work backwards from the desired quantity to find what must be computed first.",
    "Check for common traps (off-by-one, rounding) and verify the final number.",
    "Use number sense to estimate, then compute exactly and compare.",
    "Name variables for key quantities and express relationships before computing.",
    "Use proportional reasoning when appropriate; justify each proportional step.",
    "Organize solution into numbered steps, each with an explanation and result.",
    "Compute sub-results in a list, then combine them for the final value.",
    "If multiple operations are needed, annotate the order of operations explicitly.",
    "Translate sentences into equations, solve the equations, and interpret the result.",
    "Identify irrelevant information and ignore it; focus only on needed values.",
    "Use checks: re-calculate with a different method to verify.",
    "When dealing with totals, separate fixed and variable parts and sum them.",
    "For rates, convert all rates to consistent units before combining.",
    "For averages, compute total sum and divide by count; confirm count and total.",
    "For sequences, recognize the pattern and compute terms explicitly if needed.",
    "For combinatorics, count systematically to avoid double counting.",
    "For percentages, convert to decimals or fractions consistently throughout.",
    "For money problems, track dollars and cents and avoid rounding until the end.",
    "For time problems, convert all times to minutes (or hours) before computing.",
    "For distance = rate × time, compute each component and verify units.",
    "For mixtures, track quantities and concentrations precisely.",
    "For area and perimeter, write formulas and plug in values carefully.",
    "For volumes, use geometric formulas and check dimensions.",
    "For inequalities, maintain direction when multiplying by negatives.",
    "For factors and multiples, prime factorize to simplify reasoning.",
    "For remainders, use modular arithmetic when helpful.",
    "For parity, track odd/even properties of intermediate results.",
    "For fractions, reduce to simplest form only at the end.",
    "For ratios, write ratio tables and scale up or down as needed.",
    "For word problems, rephrase each sentence in math terms before computing.",
    "For multi-step discounts/taxes, apply operations in the correct order.",
    "For rounding, keep extra precision internally and round at the end.",
    "For estimation, provide an approximate value and then a precise one.",
    "For sanity checks, ensure the final magnitude makes sense.",
    "Explain each step as if teaching a student; be explicit and concise.",
    "If stuck, compute small examples to see the pattern, then generalize.",
    "Track intermediate variables with names and update them step by step.",
    "Avoid unnecessary steps; aim for minimal yet complete reasoning.",
    "At the end, summarize the reasoning and explicitly state the final answer after ####.",
    "Ensure the final answer is a single number after #### with correct sign and units if applicable.",
    "Double-check arithmetic and confirm that the answer addresses the question asked.",
    "Be consistent in formatting: steps, calculations, and final answer marker.",
]

